# Generated by Django 5.1.4 on 2024-12-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_content_article_text_remove_article_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.URLField(max_length=350),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=350),
        ),
    ]
